'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const { titlebarLogoDataUrl } = require('../app/lib/titlebar-logo')
const root = path.resolve(__dirname, '..')
test('development logo uses the checked-in PNG, not Windows ICO decoding', () => {
  const result = titlebarLogoDataUrl(path.join(root, 'app'), '', false)
  assert.ok(result.startsWith('data:image/png;base64,'))
  assert.deepEqual(Buffer.from(result.split(',')[1], 'base64'), fs.readFileSync(path.join(root, 'app/build/icon-preview.png')))
})
test('packaged logo resolves from resources and missing/corrupt assets degrade safely', t => {
  const resources = fs.mkdtempSync(path.join(os.tmpdir(), 'titlebar-logo-test-'))
  t.after(() => fs.rmSync(resources, { recursive: true, force: true }))
  assert.equal(titlebarLogoDataUrl(path.join(root, 'app'), resources, true), '')
  fs.writeFileSync(path.join(resources, 'icon-preview.png'), 'invalid')
  assert.equal(titlebarLogoDataUrl('', resources, true), '')
  fs.copyFileSync(path.join(root, 'app/build/icon-preview.png'), path.join(resources, 'icon-preview.png'))
  assert.ok(titlebarLogoDataUrl('', resources, true).startsWith('data:image/png;base64,'))
})
test('qualified packaging includes both shell assets and renderer suppresses broken-image glyphs', () => {
  const config = fs.readFileSync(path.join(root, 'electron-builder.release.cjs'), 'utf8')
  for (const name of ['icon.ico', 'icon-preview.png']) assert.ok(config.includes(`to: '${name}'`))
  const client = fs.readFileSync(path.join(root, 'app/titlebar.js'), 'utf8')
  assert.match(client, /mark\.addEventListener\('error'/)
  assert.match(client, /if \(!mark\.getAttribute\('src'\)\)/)
})
